### PR TITLE
Silent option added to not log into console

### PR DESCRIPTION
**Pull request by karolisgrinkevicius**

### CODE REVIEW

**Comment by karolisgrinkevicius** [comment]
@saf33r could you please look at this PR?

**Comment by saf33r** [comment]
Thanks @karolisgrinkevicius :+1:

**Comment by karolisgrinkevicius** [comment]
@saf33r forgot to add default parameters values in the documentation. Should I create a new PR or you're gonna do it in the future?

**Comment by saf33r** [comment]
Can you do it please?

**Comment by karolisgrinkevicius** [comment]
Ok. On Thursday I'll create one.

**Pull request merged**
